### ISSUE TITLE
Van and Cyclist

### ISSUE THREAD

**Issue by freshwk** [Ghostish/BAT#11]
Hi,if i want to train and test Van and Cyclist category ,what do I need to modify in the BAT_Car.yaml?
I am so sorry to bother you again! I am following your work and I need to do a complete experiment to test my idea.It would be better if you have time to upload the config file to github.Thank you!

**Comment by Ghostish** [comment]
You need to change the `category_name` in the BAT_Pedestrian.yaml to Cyclist / Van.

**Comment by freshwk** [comment]
> You need to change the `category_name` in the BAT_Pedestrian.yaml to Cyclist / Van.

Unfortunately，i get a much bad result  in Van category 32.85/39.88 after retraining your code .I don't know what went wrong.My configs are as follows.

#data
dataset: kitti
path: /2TB/kitti/training
category_name: Van # [Car, Van, Pedestrian, Cyclist, All]
search_bb_scale: 1.25
search_bb_offset: 2
model_bb_scale: 1.25
model_bb_offset: 0
template_size: 512
search_size: 1024
random_sample: False
sample_per_epoch: -1
degrees: True # use degrees or radians
box_aware: True
num_candidates: 4
coordinate_mode: velodyne
up_axis: [0,0,1]

#model configuration
net_model: BAT
use_fps: True
normalize_xyz: False
feature_channel: 256 #the output channel of backbone
hidden_channel: 256 #the hidden channel of xcorr
out_channel: 256 #the output channel of xcorr
vote_channel: 256 #the channel for vote aggregation
num_proposal: 64
k: 4
use_search_bc: False
use_search_feature: False
bc_channel: 9

#loss configuration
objectiveness_weight: 1.5
box_weight: 0.2
vote_weight: 1.0
seg_weight: 0.2
bc_weight: 1.0

# testing config
reference_BB: previous_result
shape_aggregation: firstandprevious
use_z: False
limit_box: True
IoU_space: 3

#training
batch_size: 50 #batch_size per gpu
workers: 10
epoch: 60
from_epoch: 0
lr: 0.001
optimizer: Adam
lr_decay_step: 12
lr_decay_rate: 0.2
wd: 0

**Comment by Ghostish** [comment]
Hello, the configuration you used to train your model is just OK. But you should use a smaller batch size (e.g. batch_size = 24 for a single GPU machine).

I just re-trained a new Van model using your configuration with the batch_size = 24. Here is the results I got:
![image](https://user-images.githubusercontent.com/7406087/135119049-ec788cb4-8fc6-4c51-9d58-ee390c739fa5.png)

By the way, since the training samples of the Van and Cyclist in the KITTI dataset are not sufficient for stable training, the test results may have a great variance across different runs. To test your model, you should focus on the Car/Pedestrian instead.
