### ISSUE TITLE
something weired while testing

### ISSUE THREAD

**Issue by freshwk** [Ghostish/BAT#9]
Hi!Last time i find that the results are different in different platform.Recently,i test the Pedestrian category with the ckpt file you provided for many times,but the results are quite different.All tests are done on the same computer(2080ti,cuda10.2,pytorch1.5) 
![image](https://user-images.githubusercontent.com/42930372/133361575-3d5e99ce-7a82-4c2f-b506-9cffbf766fa9.png)
![image](https://user-images.githubusercontent.com/42930372/133361600-b9f59271-8bd5-4ba5-b441-785c984750b2.png)
![image](https://user-images.githubusercontent.com/42930372/133361628-ead8588b-f906-4656-8b04-a068205fd949.png)
![image](https://user-images.githubusercontent.com/42930372/133361651-5c43d7c9-ac6d-476e-ae1d-876999b0a81b.png)

This does not happen to Car category.

**Comment by Ghostish** [comment]
Hi, this is due to the randomness we introduce in the Pedestrian tracking. If the predicted bbox offset is greater than the box's width or length, we will randomly set the offset to a number from -1 to 1. 
To ensure a deterministic result, you just need to set `limit_box` in the config file to `False`.
